blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://filobot.xyz/discord
    about: If you need help or can't find what you're looking for in this repository, please contact us on our Discord server.
