name: "Pull Request Operations"
on:
  pull_request_target:
    types:
    - opened
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label the PR
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true